# Generated by Django 5.1.6 on 2025-02-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='films'),
        ),
    ]
