# Generated by Django 5.1.6 on 2025-03-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmo', '0005_alter_films_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='films',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Filmo/static/media/images'),
        ),
    ]
