# Generated by Django 5.1.6 on 2025-03-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmo', '0006_users_alter_films_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
